services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: fruity
      POSTGRES_USER: candidate
      POSTGRES_PASSWORD: candidate
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U candidate -d fruity"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    restart: always
    environment:
      NODE_ENV: production
      SERVER_PORT: 3001
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: candidate
      POSTGRES_PASSWORD: candidate
      POSTGRES_DB_NAME: fruity
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data: